name: projet-serre-api
license: GPL-3.0
summary: API de communication entre le serveur et Android
description: |
  API de communication entre le serveur et Android

base: core20
grade: stable
confinement: strict

adopt-info: projet-serre

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  projet-serre:
    command: bin/projet-serre-api
    daemon: simple
    restart-condition: always
    plugs: [home, network, network-bind]
  
  projet-serre-serial-link:
    command: bin/rasp-serial
    daemon: simple
    restart-condition: always
    plugs: [home, serial-port]

slots:
  serial:
    interface: serial-port
    path: /udev/ttyACM0

parts:
  projet-serre:
    plugin: npm
    npm-node-version: "14.16.0"
    source: https://github.com/anrouxel/projet-serre-api.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    build-packages:
      - git
      - sed

  projet-serre-serial-link:
    plugin: python
    source: https://github.com/anrouxel/projet-serre-serial-link.git
    source-type: git
    python-packages: [pip, pyserial]